### ISSUE TITLE
Tracking Issues for Backends & Virtual Machines

### ISSUE THREAD

**Issue by phase** [proglangdesign/wiki#1]
This is an issue to track what backends we want to have pages for. These pages should contain resources for using the backend as well as listing languages and bindings the backend can be used with. "Caveats" and "Tips", like the current [LLVM Page](https://proglangdesign.net/wiki/llvm) has, would be helpful for comparing backends. Virtual Machines should also get pages with similar information.

---

* [x] [**LLVM**](https://llvm.org/)
  * _Bindings:_ [Go](https://github.com/llvm-mirror/llvm/tree/master/bindings/go), [OCaml](https://github.com/llvm-mirror/llvm/tree/master/bindings/ocaml), [Python](https://github.com/llvm-mirror/llvm/tree/master/bindings/python), [.NET](https://github.com/microsoft/LLVMSharp), [Haskell](https://hackage.haskell.org/package/llvm-hs), [Rust](https://crates.io/crates/llvm-sys)
* [x] **WebAssembly**
* [ ] [**CraneLift**](https://github.com/bytecodealliance/wasmtime/tree/master/cranelift)
* [ ] [**QBE**](https://c9x.me/compile/)
* [ ] [**GRIN**](https://grin-compiler.github.io/)
* [ ] **Java Virtual Machine**
  * _Libraries:_ [ASM](https://asm.ow2.io/)
* [ ] [**BEAM**](https://blog.stenmans.org/theBeamBook/)

**Comment by NilsLankila** [comment]
I've started a page for firm, see https://github.com/proglangdesign/wiki/pull/5.
